"""
Data Validation and Exploratory Data Analysis script
---------------------------------------------------
This script is automatically generated by the data-quality assistant.
It focuses on loading the provided MATLAB .mat file, inspecting its
structure, computing descriptive statistics, performing a suite of data
quality checks, and generating simple visualisations.

Outputs
=======
1. stats/statistics.json      : Descriptive statistics for each variable
2. stats/data_quality.json    : Summary of data quality checks & issues
3. figures/                   : Automatically-named PNGs for numeric vars
4. reports/data_report.md     : Human-readable EDA & quality report
5. reports/data_report.json   : Machine-readable counterpart of the report

How to run
==========
```
python code/data_validation.py --file ../data/burgers_data_R10.mat
```
The executor *should* be in the `eda` folder already, so the relative
path above ought to work.  A fallback absolute path can be provided via
`--file` if necessary.
"""

import json
import os
import sys
import argparse
import logging
from pathlib import Path
from typing import Any, Dict, List

import numpy as np
import scipy.io as sio
import matplotlib

# Use non-interactive backend in case we run headless
matplotlib.use("Agg")  # noqa: E402 after import – acceptable
import matplotlib.pyplot as plt  # noqa: E402 – isort: skip


#####################################################################
# Utility helpers
#####################################################################

def ensure_dir(path: Path):
    """Create directory if it doesn't exist."""
    path.mkdir(parents=True, exist_ok=True)


def is_numeric_array(arr: np.ndarray) -> bool:
    """Determine if numpy array is numeric (int/float/bool)."""
    return np.issubdtype(arr.dtype, np.number)


def summarise_numeric(arr: np.ndarray) -> Dict[str, Any]:
    """Return basic statistics for a numeric numpy array."""
    flat = arr.ravel()
    stats = {
        "count": int(flat.size),
        "missing": int(np.isnan(flat).sum()) if np.issubdtype(arr.dtype, np.floating) else 0,
        "mean": float(np.nanmean(flat)) if flat.size > 0 else None,
        "std": float(np.nanstd(flat)) if flat.size > 0 else None,
        "min": float(np.nanmin(flat)) if flat.size > 0 else None,
        "25%": float(np.nanpercentile(flat, 25)) if flat.size > 0 else None,
        "50%": float(np.nanpercentile(flat, 50)) if flat.size > 0 else None,
        "75%": float(np.nanpercentile(flat, 75)) if flat.size > 0 else None,
        "max": float(np.nanmax(flat)) if flat.size > 0 else None,
    }
    return stats


def detect_outliers(arr: np.ndarray, n_sigma: float = 3.0) -> Dict[str, Any]:
    """Return simple outlier metrics using mean +/- n_sigma*std criterion."""
    if not is_numeric_array(arr):
        return {}
    flat = arr.ravel()
    flat = flat[~np.isnan(flat)]  # remove NaNs for outlier detection
    if flat.size == 0:
        return {"n_outliers": 0, "pct_outliers": 0.0}
    mu, sigma = np.mean(flat), np.std(flat)
    if sigma == 0:
        return {"n_outliers": 0, "pct_outliers": 0.0}
    mask = np.abs(flat - mu) > n_sigma * sigma
    n_out = int(mask.sum())
    return {
        "n_outliers": n_out,
        "pct_outliers": float(n_out / flat.size * 100),
    }


def save_json(data: Dict[str, Any], path: Path):
    with open(path, "w", encoding="utf-8") as fp:
        json.dump(data, fp, indent=2, default=str)


#####################################################################
# Recursive .mat structure handling
#####################################################################

def matlab_to_dict(obj: Any, prefix: str = "") -> Dict[str, Any]:
    """Recursively convert MATLAB structures to nested dicts.

    We flatten the hierarchy to a single-level dict with keys like
    "parent.child.subchild" for easier downstream handling.
    """
    flat: Dict[str, Any] = {}

    if isinstance(obj, np.ndarray) and obj.dtype.names is not None:
        # Structured numpy array representing MATLAB struct array
        for name in obj.dtype.names:
            value = obj[name]
            new_prefix = f"{prefix}.{name}" if prefix else name
            flat.update(matlab_to_dict(value, new_prefix))
    elif isinstance(obj, np.ndarray) and obj.size == 1 and obj.dtype == object:
        # Possibly nested object cell – recurse into element
        flat.update(matlab_to_dict(obj.item(), prefix))
    else:
        # Base case
        flat[prefix] = obj
    return flat


#####################################################################
# Visualisation helpers
#####################################################################

def plot_histogram(arr: np.ndarray, var_name: str, out_dir: Path):
    """Plot histogram for numeric 1-D/flattened array."""
    fig, ax = plt.subplots(figsize=(6, 4))
    flat = arr.ravel()
    # Downsample if huge to keep runtime & file size reasonable
    if flat.size > 500_000:
        rng = np.random.default_rng(42)
        flat = rng.choice(flat, 500_000, replace=False)
    ax.hist(flat, bins=50, color="steelblue", edgecolor="black")
    ax.set_title(f"Histogram of {var_name}")
    ax.set_xlabel(var_name)
    ax.set_ylabel("Frequency")
    fig.tight_layout()
    fig_path = out_dir / f"{var_name}_hist.png"
    fig.savefig(fig_path, dpi=150)
    plt.close(fig)


#####################################################################
# Main EDA / validation routine
#####################################################################

def run_validation(mat_file: str):
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    mat_path = Path(mat_file)
    if not mat_path.exists():
        logging.error("File not found: %s", mat_file)
        sys.exit(1)

    # Ensure output directories exist
    stats_dir = Path("stats")
    figs_dir = Path("figures")
    reports_dir = Path("reports")
    for d in (stats_dir, figs_dir, reports_dir):
        ensure_dir(d)

    logging.info("Loading MATLAB file: %s", mat_file)
    try:
        mat_data = sio.loadmat(mat_path, struct_as_record=False, squeeze_me=True)
    except Exception as exc:
        logging.exception("Failed to load .mat file: %s", exc)
        sys.exit(1)

    # Remove default MATLAB metadata keys that start with '__'
    mat_data = {k: v for k, v in mat_data.items() if not k.startswith("__")}

    # Flatten nested structures
    flat_data: Dict[str, Any] = {}
    for key, value in mat_data.items():
        flat_data.update(matlab_to_dict(value, prefix=key))

    variable_stats: Dict[str, Any] = {}
    quality_issues: Dict[str, Any] = {}

    for var_name, obj in flat_data.items():
        entry: Dict[str, Any] = {
            "type": str(type(obj)),
        }
        quality_entry: Dict[str, Any] = {}

        if isinstance(obj, np.ndarray):
            entry["shape"] = obj.shape
            entry["dtype"] = str(obj.dtype)
            entry["size_bytes"] = int(obj.nbytes)

            if is_numeric_array(obj):
                stats_dict = summarise_numeric(obj)
                entry.update(stats_dict)
                # Visualisation
                try:
                    plot_histogram(obj, var_name, figs_dir)
                except Exception as exc:
                    logging.warning("Failed to plot %s: %s", var_name, exc)

                # Outliers
                quality_entry.update(detect_outliers(obj))

                # Missing
                quality_entry["missing_values"] = int(np.isnan(obj).sum())
            else:
                entry["note"] = "Non-numeric array – stats limited"
        else:
            # Non-array objects – basic representation only
            try:
                entry["value_preview"] = str(obj)[:200]
            except Exception:
                entry["value_preview"] = "<unserialisable>"

        variable_stats[var_name] = entry
        if quality_entry:
            quality_issues[var_name] = quality_entry

    # Simple summary of file size & memory footprint
    overall_summary = {
        "file": str(mat_path),
        "file_size_bytes": mat_path.stat().st_size,
        "n_variables": len(variable_stats),
        "total_memory_in_arrays": int(sum(v.get("size_bytes", 0) for v in variable_stats.values())),
    }

    #############################################################
    # Save outputs
    #############################################################
    stats_json = {
        "summary": overall_summary,
        "variables": variable_stats,
    }
    quality_json = {
        "summary": overall_summary,
        "issues": quality_issues,
    }

    save_json(stats_json, stats_dir / "statistics.json")
    save_json(quality_json, stats_dir / "data_quality.json")

    # Human-readable Markdown report
    md_lines: List[str] = []
    md_lines.append(f"# Data Report for {mat_path.name}\n")
    md_lines.append("## Overall Summary\n")
    md_lines.append(json.dumps(overall_summary, indent=2))

    md_lines.append("\n## Variables\n")
    for var, info in variable_stats.items():
        md_lines.append(f"### {var}\n")
        md_lines.append("```")
        md_lines.append(json.dumps(info, indent=2))
        md_lines.append("```\n")
        if var in quality_issues:
            md_lines.append("**Quality checks:**\n")
            md_lines.append("```")
            md_lines.append(json.dumps(quality_issues[var], indent=2))
            md_lines.append("```\n")

    report_md = "\n".join(md_lines)
    (reports_dir / "data_report.md").write_text(report_md, encoding="utf-8")
    save_json({"markdown_report": report_md}, reports_dir / "data_report.json")

    logging.info("EDA & validation complete. Outputs saved to stats/, figures/, reports/.")


#####################################################################
# CLI entry point
#####################################################################

def main():
    parser = argparse.ArgumentParser(description="Data Validation and EDA for MATLAB file")
    parser.add_argument("--file", required=True, help="Path to .mat file (relative to current directory)")
    args = parser.parse_args()
    run_validation(args.file)


if __name__ == "__main__":
    main()
