# generate_report.py
"""Iterative Report Builder
This script reads statistics and figures generated by the EDA pipeline and
automatically creates a new versioned Markdown report that complies with the
"ITERATIVE REPORT CREATION" rules provided in the developer instructions.

Usage (from eda folder):
    python code/generate_report.py
"""

import json
from datetime import datetime
from pathlib import Path

REPORTS_DIR = Path("reports")
FIGURES_DIR = Path("figures")
STATS_FILE = Path("stats/statistics.json")

# -------------------------------------------------------------------------------------------------
# Helper Functions
# -------------------------------------------------------------------------------------------------

def next_version() -> int:
    """Determine the next report version number (v1, v2, ...)"""
    versions = []
    for p in REPORTS_DIR.glob("data_report_v*.md"):
        try:
            v = int(p.stem.split("_v")[-1])
            versions.append(v)
        except ValueError:
            continue
    return (max(versions) + 1) if versions else 1


def load_statistics() -> dict:
    if not STATS_FILE.exists():
        raise FileNotFoundError("stats/statistics.json not found. Run EDA first.")
    with open(STATS_FILE) as f:
        return json.load(f)


def list_figures() -> list:
    return sorted([p.name for p in FIGURES_DIR.glob("*.png")])


# -------------------------------------------------------------------------------------------------
# Markdown Builders
# -------------------------------------------------------------------------------------------------

def build_basic_stats_section(stats_obj: dict) -> str:
    lines = ["## Basic Statistics\n"]
    for var, metrics in stats_obj.get("basic_stats", {}).items():
        lines.append(f"### Variable: {var}\n")
        for k, v in metrics.items():
            lines.append(f"* **{k}**: {v}")
        lines.append("")
    return "\n".join(lines)


def build_advanced_section(stats_obj: dict) -> str:
    adv = stats_obj.get("advanced_stats", {})
    lines = ["## Advanced Analysis\n"]

    # Correlations
    corrs = adv.get("correlations", {})
    if corrs:
        lines.append("### Correlation Analysis\n")
        for m in ["pearson", "spearman"]:
            if m in corrs and corrs[m]:
                fig_name = f"corr_{m}.png"
                lines.append(f"![{m.title()} Correlation Matrix](../figures/{fig_name})\n")
    # Spectral
    if adv.get("spectral"):
        lines.append("### Spectral Analysis\n")
        for var, d in adv["spectral"].items():
            fig_name = f"spectral_{var}.png"
            lines.append(f"#### {var}\n")
            lines.append(f"![Power Spectrum – {var}](../figures/{fig_name})\n")
            lines.append(f"Dominant frequency: **{d['dominant_frequency']:.4f}**, Max power: **{d['max_power']:.4e}**\n")
    # Gradient
    if adv.get("gradient"):
        lines.append("### Gradient Analysis\n")
        for var, d in adv["gradient"].items():
            lines.append(f"* **{var}** – min: {d.get('gradient_min')}, max: {d.get('gradient_max')}, mean: {d.get('gradient_mean')}\n")

    return "\n".join(lines)


def build_visualization_section(fig_files: list) -> str:
    lines = ["## Visualizations\n"]
    for fig in fig_files:
        desc = fig.replace("_", " ").replace(".png", "").title()
        lines.append(f"![{desc}](../figures/{fig})\n")
    return "\n".join(lines)


def build_appendix(fig_files: list) -> str:
    lines = ["## Appendix: Figure List\n", "| # | Filename | Description |", "|---|----------|-------------|"]
    for idx, fig in enumerate(fig_files, 1):
        desc = fig.replace("_", " ").replace(".png", "").title()
        lines.append(f"| {idx} | {fig} | {desc} |")
    return "\n".join(lines)


# -------------------------------------------------------------------------------------------------
# Main builder
# -------------------------------------------------------------------------------------------------

def build_report():
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    version = next_version()
    stats_obj = load_statistics()
    fig_files = list_figures()

    md_parts = [
        f"# Data Report – Version {version}\n",
        f"_Generated: {datetime.now().isoformat()}_\n",
        "\n## Executive Summary\n",
        "This report presents descriptive statistics, advanced analyses, and visual insights derived from the latest data processing run.\n",
        build_basic_stats_section(stats_obj),
        build_advanced_section(stats_obj),
        build_visualization_section(fig_files),
        build_appendix(fig_files),
    ]

    markdown_content = "\n".join(md_parts)

    # JSON summary simply re-export stats plus metadata
    json_content = {
        "version": version,
        "generated": datetime.now().isoformat(),
        **stats_obj,
    }

    # Save files
    md_path = REPORTS_DIR / f"data_report_v{version}.md"
    json_path = REPORTS_DIR / f"data_report_v{version}.json"

    with md_path.open("w", encoding="utf-8") as f:
        f.write(markdown_content)
    with json_path.open("w", encoding="utf-8") as f:
        json.dump(json_content, f, indent=2)

    # Also update latest aliases
    (REPORTS_DIR / "data_report_latest.md").write_text(markdown_content, encoding="utf-8")
    (REPORTS_DIR / "data_report_latest.json").write_text(json.dumps(json_content, indent=2), encoding="utf-8")

    print(f"Report v{version} saved: {md_path}")


if __name__ == "__main__":
    build_report()
